---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-project-onboarding
  namespace: openshift-gitops
  labels:
    type: application
spec:
  destination:
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: .
    repoURL: "https://github.com/Vikaspogu/tenants-iac-gitops.git"
    targetRevision: main
    plugin:
      name: helm-multivalues-plugin
      env:
        - name: CHART_REPO_URL
          value: https://github.com/devhub-showcase/shared-helm-charts.git
        - name: CHART_PATH
          value: helm/charts/project-onboarding
        - name: VALUES_FOLDER
          value: clusters/dev-acm/team-a-application/project-onboarding-values/apps
        - name: VALUES_FILE
          value: clusters/dev-acm/team-a-application/project-onboarding-values/values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - Validate=false
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - Prune=true
