apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "team-alpha-cicd-cluster-reader"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
  - kind: ServiceAccount
    name: team-alpha-cicd-argocd-application-controller
    namespace: team-alpha-cicd
  - kind: ServiceAccount
    name: team-alpha-cicd-argocd-server
    namespace: team-alpha-cicd
