---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: was-app-secret
  namespace: was-vm-team-b
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: was-app-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: vm-user-password