---
apiVersion: 'kubevirt.io/v1'
kind: 'VirtualMachine'
metadata:
  labels:
    app: was-app
    kubevirt.io/dynamic-credentials-support: 'true'
    vm.kubevirt.io/template: 'fedora-server-small'
    vm.kubevirt.io/template.namespace: 'openshift'
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: 'v0.27.0'
  name: was-app
  namespace: was-vm-team-b
spec:
  dataVolumeTemplates:
    - apiVersion: 'cdi.kubevirt.io/v1beta1'
      kind: 'DataVolume'
      metadata:
        creationTimestamp: null
        name: was-app
      spec:
        source:
          http:
            url: https://dl.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2
        storage:
          resources:
            requests:
              storage: '30Gi'
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: 'small'
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: 'server'
      creationTimestamp: null
      labels:
        kubevirt.io/domain: was-app
        kubevirt.io/size: 'small'
    spec:
      accessCredentials:
        - userPassword:
            propagationMethod:
              qemuGuestAgent: {}
            source:
              secret:
                secretName: was-app-secret
      architecture: 'amd64'
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: 'virtio'
              name: 'rootdisk'
            - disk:
                bus: 'virtio'
              name: 'cloudinitdisk'
          interfaces:
            - masquerade: {}
              model: 'virtio'
              name: 'default'
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: 'pc-q35-rhel9.2.0'
        memory:
          guest: '2Gi'
        resources: {}
      networks:
        - name: 'default'
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: was-app
          name: 'rootdisk'
        - cloudInitNoCloud:
            userData: "#cloud-config\nuser: admin\nchpasswd: { expire: False }"
          name: 'cloudinitdisk'
---
apiVersion: v1
kind: Namespace
metadata:
  name: was-vm-team-b
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops