{{- $namespaces := list -}}
{{- range $key, $apps := .Values.apps}}
{{- range $appNamespace := $apps.namespaces }}
{{- if has $appNamespace $namespaces -}}
{{- else -}}
{{ $namespaces = append $namespaces $appNamespace }}
{{- end }}
{{- end }}
{{- end }}
---
kind: ArgoCD
apiVersion: argoproj.io/v1beta1
metadata:
  name: {{.Values.team}}-gitops
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "project-onboarding.labels" . | nindent 4 }}
spec:
  resourceTrackingMethod: annotation
  kustomizeBuildOptions: --enable-alpha-plugins --load-restrictor LoadRestrictionsNone --helm-command /usr/local/bin/helm
  extraConfig:
    accounts.developer-hub: apiKey, login
    resource.compareoptions: |
      ignoreAggregatedRoles: true
  sourceNamespaces:
  {{- range $namespace := $namespaces}}
    - {{ $namespace }}
  {{- end }}
  controller:
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
  applicationInstanceLabelKey: {{.Values.team}}-gitops
  applicationSet:
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  rbac:
    defaultPolicy: ""
    policy: |
      g, system:cluster-admins, role:admin
      g, openshift-admins, role:admin
      g, developer-hub, role:readonly
    scopes: "[groups]"
  sso:
    dex:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
      openShiftOAuth: true
    provider: dex
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  server:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    insecure: true
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
