{{- $releaseLabels := include "project-onboarding.labels" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: developer-hub-user
  namespace: {{ .Values.namespace }}
  labels: {{- $releaseLabels | nindent 4 }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "developer-hub/developer-hub-user"
data:
  password: "" 
