{{- $releaseLabels := include "team-onboarding.labels" . -}}
{{- $values := .Values -}}
{{- range $key, $apps := .Values.apps}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}-build
  namespace: {{ $values.namespace }}
  labels:
    {{- $releaseLabels | nindent 4 }}
    {{ $values.team }}-gitops: {{$key}}
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ $values.namespace }}
  project: {{ $key }}
  sources:
    - helm:
        releaseName: {{$key}}
        valueFiles:
          - $values/{{$apps.tenantGitops.path}}/build/build-values.yaml
      path: charts/build-pipeline
      repoURL: "{{$apps.helmChartRepo}}"
      targetRevision: main
    - ref: values
      repoURL: {{$apps.tenantGitops.repo}}
      targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - Validate=false
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - Prune=true
{{- end }}
