{{- $releaseLabels := include "team-onboarding.labels" . -}}
{{- $values := .Values -}}
{{- range $key, $apps := .Values.apps}}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $key }}-deploy-app-set
  namespace: {{ $values.namespace }}
  labels:
    {{- $releaseLabels | nindent 4 }}
    {{ $values.team }}-cicd: {{$key}}
spec:
  generators:
    - git:
        repoURL: {{$apps.tenantGitops.repo}}
        revision: HEAD
        files:
          - path: "{{$apps.tenantGitops.path}}/deploy/*.yaml"
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: {{ $key }}-{{`{{ .path.filename | splitList "-" | first }}` }}
      labels:
        {{ $values.team }}-cicd: {{$key}}
      annotations:
        argocd-image-updater.argoproj.io/image-list: main=quay.io/rhn_gps_vpogu/{{$key}}:test
        argocd-image-updater.argoproj.io/main.update-strategy: newest-build
        argocd-image-updater.argoproj.io/write-back-method: git:secret:openshift-gitops/git-creds
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/git-repository: {{$apps.tenantGitops.repo}}
        argocd-image-updater.argoproj.io/write-back-target: "helmvalues:../../{{`{{ .path.path }}/{{.path.filename}}`}}"
        argocd-image-updater.argoproj.io/main.helm.image-tag: image.tag
        argocd-image-updater.argoproj.io/main.helm.image-name: image.repository
        argocd-image-updater.argoproj.io/force-update: "true"
    spec:
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{ trimSuffix "-cicd" $values.namespace }}-{{`{{ .path.filename | splitList "-" | first }}` }}'
      project: {{ $key }}
      sources:
        - helm:
            releaseName: {{$key}}
            valueFiles:
              - "$values/{{`{{ .path.path }}/{{.path.filename}}`}}"
          path: charts/deploy
          repoURL: "{{$apps.helmChartRepo}}"
          targetRevision: main
        - ref: values
          repoURL: {{$apps.tenantGitops.repo}}
          targetRevision: main
      syncPolicy:
        managedNamespaceMetadata:
          labels: 
            argocd.argoproj.io/managed-by: {{ $values.team }}-cicd
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - SkipDryRunOnMissingResource=true
          - Validate=false
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
          - Prune=true
{{- end }}
