{{- $releaseLabels := include "team-onboarding.labels" . -}}
{{- $gitopsNamespace := .Values.namespace -}}
{{- range $key, $apps := .Values.apps}}
{{- range $namespace := $apps.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $namespace }}-pipeline-edit
  namespace: {{ $namespace }}
  labels:
    {{- $releaseLabels | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ $gitopsNamespace }}
{{- end }}
{{- end }}